#!/usr/bin/env bash

# QUICK START GUIDE - Color formatted output

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   END-TO-END DATA SCIENCE PROJECT - QUICK START GUIDE          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "\n${YELLOW}📋 PROJECT OVERVIEW${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Complete Data Science Pipeline (Data → Model → API)"
echo "✓ Pre-trained Model Ready to Use"
echo "✓ Flask & FastAPI Deployment"
echo "✓ Optimized for Google Colab"
echo "✓ Production-Ready Code"

echo -e "\n${YELLOW}🚀 OPTION 1: GOOGLE COLAB (RECOMMENDED)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://colab.research.google.com/"
echo "2. Click: File → Open notebook → Upload"
echo "3. Select: END_TO_END_COLAB_NOTEBOOK.ipynb"
echo "4. Click: Runtime → Run all"
echo "5. ✅ Done! Model is trained & predictions work"

echo -e "\n${YELLOW}🚀 OPTION 2: LOCAL SETUP${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo -e "\n${GREEN}Step 1: Install Dependencies${NC}"
echo "bash"
echo "  pip install -r requirements.txt"
echo ""

echo -e "${GREEN}Step 2: Train Model (or skip if already trained)${NC}"
echo "bash"
echo "  python model_trainer.py"
echo ""

echo -e "${GREEN}Step 3a: Start Flask API${NC}"
echo "bash"
echo "  python flask_app.py"
echo ""
echo "Then visit: ${BLUE}http://localhost:5000${NC}"
echo ""

echo -e "${GREEN}Step 3b: OR Start FastAPI${NC}"
echo "bash"
echo "  uvicorn fastapi_app:app --reload"
echo ""
echo "Then visit: ${BLUE}http://localhost:8000/docs${NC}"
echo ""

echo -e "\n${YELLOW}📡 API ENDPOINTS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "GET  /              - API Documentation"
echo "GET  /health        - Health Check"
echo "GET  /features      - Feature Information"
echo "GET  /model-info    - Model Details"
echo "POST /predict       - Single Prediction"
echo "POST /predict-batch - Batch Predictions"

echo -e "\n${YELLOW}🧪 TEST THE API${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "bash"
echo "  python test_api.py"
echo ""

echo -e "${YELLOW}🐳 OPTION 3: DOCKER${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "bash"
echo "  # Single API"
echo "  docker build -t ml-api ."
echo "  docker run -p 5000:5000 ml-api"
echo ""
echo "  # Or use Docker Compose (both APIs)"
echo "  docker-compose up"
echo ""

echo -e "\n${YELLOW}📁 PROJECT FILES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Core Files:"
echo "  ├── END_TO_END_COLAB_NOTEBOOK.ipynb ← Start here for Colab"
echo "  ├── model_trainer.py                 ← Training pipeline"
echo "  ├── flask_app.py                     ← Flask API"
echo "  ├── fastapi_app.py                   ← FastAPI alternative"
echo "  ├── test_api.py                      ← API tests"
echo "  ├── test_project.py                  ← Project tests"
echo "  ├── examples.py                      ← Usage examples"
echo "  ├── utils.py                         ← Utility functions"
echo "  ├── config.py                        ← Configuration"
echo "  └── requirements.txt                 ← Dependencies"
echo ""
echo "Configuration:"
echo "  ├── Dockerfile                       ← Docker container"
echo "  ├── docker-compose.yml               ← Multi-service Docker"
echo "  ├── Procfile                         ← Heroku deployment"
echo "  ├── runtime.txt                      ← Python version"
echo "  └── .env.example                     ← Environment template"
echo ""
echo "Documentation:"
echo "  ├── README.md                        ← Overview"
echo "  ├── DEPLOYMENT_GUIDE.md              ← Detailed guide"
echo "  └── build.sh                         ← Build script"
echo ""
echo "Generated:"
echo "  ├── model.pkl                        ← Trained model"
echo "  └── scaler.pkl                       ← Feature scaler"
echo ""

echo -e "\n${YELLOW}🌐 CLOUD DEPLOYMENT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Heroku (Free):"
echo "  git push heroku main"
echo ""
echo "Railway (Easy):"
echo "  Connect GitHub repo → Auto-deploys"
echo ""
echo "AWS Lambda (Serverless):"
echo "  zappa deploy dev"
echo ""

echo -e "\n${YELLOW}📊 MODEL PERFORMANCE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Model: Random Forest Regressor"
echo "Dataset: Diabetes (442 samples, 10 features)"
echo "Test R² Score: 0.5773"
echo "RMSE: 59.38"
echo "Training Time: < 2 seconds"
echo "Prediction Time: < 10ms"

echo -e "\n${YELLOW}✨ EXAMPLE USAGE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Python:${NC}"
echo "import requests"
echo "response = requests.post('http://localhost:5000/predict',"
echo "  json={'features': [0.05, -0.05, 0.03, -0.02, 0.01, "
echo "                     -0.04, 0.02, -0.03, 0.04, -0.01]})"
echo "print(response.json())"
echo ""
echo -e "${GREEN}cURL:${NC}"
echo "curl -X POST http://localhost:5000/predict \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"features\": [0.05, -0.05, 0.03, -0.02, 0.01,"
echo "       -0.04, 0.02, -0.03, 0.04, -0.01]}'"
echo ""

echo -e "\n${YELLOW}📚 LEARNING OUTCOMES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Complete ML pipeline development"
echo "✓ Data preprocessing & feature scaling"
echo "✓ Model training & evaluation"
echo "✓ REST API development (Flask & FastAPI)"
echo "✓ Model serialization & deployment"
echo "✓ Cloud deployment strategies"
echo "✓ API testing & validation"

echo -e "\n${YELLOW}⚡ QUICK COMMANDS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Run all components"
echo "bash build.sh"
echo ""
echo "# Run examples"
echo "python examples.py"
echo ""
echo "# Check project"
echo "python test_project.py"
echo ""

echo -e "\n${GREEN}✅ PROJECT IS READY!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${BLUE}Choose your starting option:${NC}"
echo "  1. 🎯 Google Colab (Easiest)    → Upload END_TO_END_COLAB_NOTEBOOK.ipynb"
echo "  2. 🖥️  Local Flask API           → python flask_app.py"
echo "  3. ⚡ Local FastAPI             → uvicorn fastapi_app:app --reload"
echo "  4. 🐳 Docker                    → docker build -t ml-api . && docker run -p 5000:5000 ml-api"
echo ""
echo -e "${BLUE}For detailed guide, see: DEPLOYMENT_GUIDE.md${NC}"
echo ""
